### ISSUE TITLE
Error When trying to BIND bones.

### ISSUE THREAD

**Issue by Mehdianim** [anasrar/ReNim#11]
Tried this with Blender 2.8 and 3.0
I am binding an imported skeleton with mocap animation on it (Source)
to a Library Override Character Contro Rig (Target)
I set up the nodes, assign them each to the correct Target and Source slots
I can create the Bone Node from Selected Nodes.
When I press BIND I get this Error:
![image](https://user-images.githubusercontent.com/45181118/151704985-75feb1dd-c01e-4d59-b0a9-6f36cd8b455c.png)

If there is no support for working with Library overrides it would be a great feature to add. My whole pipeline is built to animate with Library override rigs so that I can update improve the one rig and automatically see it updated in various animation scenes.

**Comment by anasrar** [comment]
unfortunately Blender not support edit mode on Library override object, that is why the error say `Unable to execute 'Toggle Edit Mode', error changing modes`
[https://blenderartists.org/t/will-blenders-library-override-eventually-support-edit-mode-and-sculpt-mode-to-create-shape-keys/1307618/24](https://blenderartists.org/t/will-blenders-library-override-eventually-support-edit-mode-and-sculpt-mode-to-create-shape-keys/1307618/24)
this is current Blender limitation, for workflow you can import/append rig and then retarget and bake the action on another blend file and then import the action
