### ISSUE TITLE
Mapping not work when object is binded

### ISSUE THREAD

**Issue by romkas27** [anasrar/ReNim#12]
Blender 4.1, addon version 0.1.4. Nothing happens after pressing the Bind button - source bones are moving, target bones remain motionless.

video https://github.com/anasrar/ReNim/assets/42959731/f6c1f9dc-6d4d-4d9d-87cf-ef4881dea4fb

file https://www.dropbox.com/scl/fi/8qaadu1lix5yv2656ha2h/RENIM-issue.blend?rlkey=gss9ot4cpfr68j408ncfqc622&dl=0

**Comment by anasrar** [comment]
Thanks for the report, I found the issue is you can not do mapping when the state is bind, so you have to mapping on unbind state.

Working on fixing this issue tomorrow.

https://github.com/anasrar/ReNim/assets/38805204/4d300c68-93b6-4fd8-aae3-5c9e26ba3dd4

**Comment by romkas27** [comment]
I'm sorry, I watched the tutorial and it said to BIND rigs at first and then to mapping. Now everything is fine. Thank you for your addon, it`s very simple and powerful )

  
>Среда, 3 апреля 2024, 19:44 +10:00 от Anas Rin ***@***.***>:
> 
> 
>Thanks for the report, I found the issue is you can not do mapping when the state is bind, so you have to mapping on unbind state.
>Working on fixing this issue tomorrow.
>https://github.com/anasrar/ReNim/assets/38805204/4d300c68-93b6-4fd8-aae3-5c9e26ba3dd4
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <anasrar/ReNim/issues/12/2034075840 @ github . com> 
 
 
Роман Че

**Comment by anasrar** [comment]
@romkas27 no need to sorry, Blender 4 change bone layer to bone collection, that was my mistake not look into the detail.
